#############################################################################
# Makefile for building: PinpointWCS.app/Contents/MacOS/PinpointWCS
# Generated by qmake (2.01a) (Qt 4.7.3) on: Fri Jul 8 18:59:56 2011
# Project:  PinpointWCS.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile PinpointWCS.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DMAC_ENV=1 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.7/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I. -Igui -Ibackend -I../cfitsio/include -I../libwcs -I../eigen -I../XMP-Toolkit-SDK-5.1.2/public/include -I../xpa-2.1.13/include -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -L../cfitsio/lib -lcfitsio -L../libwcs -lwcs -lm -L../XMP-Toolkit-SDK-5.1.2/public/libraries/macintosh/release -lXMPCoreStaticRelease -lXMPFilesStaticRelease -framework CoreServices -L../xpa-2.1.13/lib -lxpa -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		backend/ComputeWCS.cpp \
		backend/CoordinateDelegate.cpp \
		backend/CoordinateModel.cpp \
		backend/DS9Thread.cpp \
		backend/EpoImage.cpp \
		backend/ExportWCS.cpp \
		backend/FitsImage.cpp \
		backend/FITSThread.cpp \
		backend/PinpointWCSUtils.cpp \
		backend/PPWcsImage.cpp \
		gui/AboutDialog.cpp \
		gui/Commands.cpp \
		gui/CoordinateMarker.cpp \
		gui/CoordinatePanel.cpp \
		gui/CoordinateTableDialog.cpp \
		gui/DropArea.cpp \
		gui/FitsToolbar.cpp \
		gui/GraphicsScene.cpp \
		gui/GraphicsView.cpp \
		gui/HelpPanel.cpp \
		gui/mainwindow.cpp \
		gui/MessageBox.cpp \
		gui/WcsInfoPanel.cpp moc_ComputeWCS.cpp \
		moc_CoordinateDelegate.cpp \
		moc_CoordinateModel.cpp \
		moc_DS9Thread.cpp \
		moc_EpoImage.cpp \
		moc_ExportWCS.cpp \
		moc_FitsImage.cpp \
		moc_FITSThread.cpp \
		moc_PPWcsImage.cpp \
		moc_AboutDialog.cpp \
		moc_CoordinatePanel.cpp \
		moc_CoordinateTableDialog.cpp \
		moc_DropArea.cpp \
		moc_FitsToolbar.cpp \
		moc_GraphicsScene.cpp \
		moc_GraphicsView.cpp \
		moc_HelpPanel.cpp \
		moc_mainwindow.cpp \
		moc_MessageBox.cpp \
		moc_WcsInfoPanel.cpp \
		qrc_PinpointWCS.cpp
OBJECTS       = main.o \
		ComputeWCS.o \
		CoordinateDelegate.o \
		CoordinateModel.o \
		DS9Thread.o \
		EpoImage.o \
		ExportWCS.o \
		FitsImage.o \
		FITSThread.o \
		PinpointWCSUtils.o \
		PPWcsImage.o \
		AboutDialog.o \
		Commands.o \
		CoordinateMarker.o \
		CoordinatePanel.o \
		CoordinateTableDialog.o \
		DropArea.o \
		FitsToolbar.o \
		GraphicsScene.o \
		GraphicsView.o \
		HelpPanel.o \
		mainwindow.o \
		MessageBox.o \
		WcsInfoPanel.o \
		moc_ComputeWCS.o \
		moc_CoordinateDelegate.o \
		moc_CoordinateModel.o \
		moc_DS9Thread.o \
		moc_EpoImage.o \
		moc_ExportWCS.o \
		moc_FitsImage.o \
		moc_FITSThread.o \
		moc_PPWcsImage.o \
		moc_AboutDialog.o \
		moc_CoordinatePanel.o \
		moc_CoordinateTableDialog.o \
		moc_DropArea.o \
		moc_FitsToolbar.o \
		moc_GraphicsScene.o \
		moc_GraphicsView.o \
		moc_HelpPanel.o \
		moc_mainwindow.o \
		moc_MessageBox.o \
		moc_WcsInfoPanel.o \
		qrc_PinpointWCS.o
DIST          = /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/release.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		PinpointWCS.pro
QMAKE_TARGET  = PinpointWCS
DESTDIR       = 
TARGET        = PinpointWCS.app/Contents/MacOS/PinpointWCS

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile PinpointWCS.app/Contents/PkgInfo PinpointWCS.app/Contents/Resources/empty.lproj PinpointWCS.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_AboutDialog.h ui_CoordinatePanel.h ui_CoordinateTableDialog.h ui_FitsToolbar.h ui_HelpPanel.h ui_PinpointWCS.h ui_WcsInfoPanel.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) PinpointWCS.app/Contents/MacOS/ || $(MKDIR) PinpointWCS.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PinpointWCS.pro  /usr/local/Qt4.7/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/release.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile PinpointWCS.pro
/usr/local/Qt4.7/mkspecs/common/unix.conf:
/usr/local/Qt4.7/mkspecs/common/mac.conf:
/usr/local/Qt4.7/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.7/mkspecs/qconfig.pri:
/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.7/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.7/mkspecs/features/qt_config.prf:
/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.7/mkspecs/features/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/release.prf:
/usr/local/Qt4.7/mkspecs/features/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.7/mkspecs/features/warn_on.prf:
/usr/local/Qt4.7/mkspecs/features/qt.prf:
/usr/local/Qt4.7/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.7/mkspecs/features/moc.prf:
/usr/local/Qt4.7/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.7/mkspecs/features/resources.prf:
/usr/local/Qt4.7/mkspecs/features/uic.prf:
/usr/local/Qt4.7/mkspecs/features/yacc.prf:
/usr/local/Qt4.7/mkspecs/features/lex.prf:
/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile PinpointWCS.pro

PinpointWCS.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) PinpointWCS.app/Contents || $(MKDIR) PinpointWCS.app/Contents 
	@$(DEL_FILE) PinpointWCS.app/Contents/PkgInfo
	@echo "APPL????" >PinpointWCS.app/Contents/PkgInfo
PinpointWCS.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) PinpointWCS.app/Contents/Resources || $(MKDIR) PinpointWCS.app/Contents/Resources 
	@touch PinpointWCS.app/Contents/Resources/empty.lproj
	
PinpointWCS.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) PinpointWCS.app/Contents || $(MKDIR) PinpointWCS.app/Contents 
	@$(DEL_FILE) PinpointWCS.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,PinpointWCS,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.7/mkspecs/macx-g++/Info.plist.app >PinpointWCS.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/PinpointWCS1.0.0 || $(MKDIR) .tmp/PinpointWCS1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PinpointWCS1.0.0/ && $(COPY_FILE) --parents version.h backend/ComputeWCS.h backend/CoordinateDelegate.h backend/CoordinateModel.h backend/DS9Thread.h backend/EpoImage.h backend/ExportWCS.h backend/FitsImage.h backend/FITSThread.h backend/PinpointWCSUtils.h backend/PPWcsImage.h gui/AboutDialog.h gui/Commands.h gui/CoordinateMarker.h gui/CoordinatePanel.h gui/CoordinateTableDialog.h gui/DropArea.h gui/FitsToolbar.h gui/GraphicsScene.h gui/GraphicsView.h gui/HelpPanel.h gui/mainwindow.h gui/MessageBox.h gui/WcsInfoPanel.h .tmp/PinpointWCS1.0.0/ && $(COPY_FILE) --parents PinpointWCS.qrc .tmp/PinpointWCS1.0.0/ && $(COPY_FILE) --parents main.cpp backend/ComputeWCS.cpp backend/CoordinateDelegate.cpp backend/CoordinateModel.cpp backend/DS9Thread.cpp backend/EpoImage.cpp backend/ExportWCS.cpp backend/FitsImage.cpp backend/FITSThread.cpp backend/PinpointWCSUtils.cpp backend/PPWcsImage.cpp gui/AboutDialog.cpp gui/Commands.cpp gui/CoordinateMarker.cpp gui/CoordinatePanel.cpp gui/CoordinateTableDialog.cpp gui/DropArea.cpp gui/FitsToolbar.cpp gui/GraphicsScene.cpp gui/GraphicsView.cpp gui/HelpPanel.cpp gui/mainwindow.cpp gui/MessageBox.cpp gui/WcsInfoPanel.cpp .tmp/PinpointWCS1.0.0/ && $(COPY_FILE) --parents gui/AboutDialog.ui gui/CoordinatePanel.ui gui/CoordinateTableDialog.ui gui/FitsToolbar.ui gui/HelpPanel.ui gui/PinpointWCS.ui gui/WcsInfoPanel.ui .tmp/PinpointWCS1.0.0/ && (cd `dirname .tmp/PinpointWCS1.0.0` && $(TAR) PinpointWCS1.0.0.tar PinpointWCS1.0.0 && $(COMPRESS) PinpointWCS1.0.0.tar) && $(MOVE) `dirname .tmp/PinpointWCS1.0.0`/PinpointWCS1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PinpointWCS1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r PinpointWCS.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_ComputeWCS.cpp moc_CoordinateDelegate.cpp moc_CoordinateModel.cpp moc_DS9Thread.cpp moc_EpoImage.cpp moc_ExportWCS.cpp moc_FitsImage.cpp moc_FITSThread.cpp moc_PPWcsImage.cpp moc_AboutDialog.cpp moc_CoordinatePanel.cpp moc_CoordinateTableDialog.cpp moc_DropArea.cpp moc_FitsToolbar.cpp moc_GraphicsScene.cpp moc_GraphicsView.cpp moc_HelpPanel.cpp moc_mainwindow.cpp moc_MessageBox.cpp moc_WcsInfoPanel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ComputeWCS.cpp moc_CoordinateDelegate.cpp moc_CoordinateModel.cpp moc_DS9Thread.cpp moc_EpoImage.cpp moc_ExportWCS.cpp moc_FitsImage.cpp moc_FITSThread.cpp moc_PPWcsImage.cpp moc_AboutDialog.cpp moc_CoordinatePanel.cpp moc_CoordinateTableDialog.cpp moc_DropArea.cpp moc_FitsToolbar.cpp moc_GraphicsScene.cpp moc_GraphicsView.cpp moc_HelpPanel.cpp moc_mainwindow.cpp moc_MessageBox.cpp moc_WcsInfoPanel.cpp
moc_ComputeWCS.cpp: backend/ComputeWCS.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ backend/ComputeWCS.h -o moc_ComputeWCS.cpp

moc_CoordinateDelegate.cpp: gui/GraphicsScene.h \
		gui/CoordinateMarker.h \
		gui/GraphicsView.h \
		backend/CoordinateDelegate.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ backend/CoordinateDelegate.h -o moc_CoordinateDelegate.cpp

moc_CoordinateModel.cpp: gui/Commands.h \
		gui/GraphicsScene.h \
		gui/CoordinateMarker.h \
		gui/GraphicsView.h \
		backend/CoordinateModel.h \
		backend/CoordinateDelegate.h \
		backend/ComputeWCS.h \
		backend/CoordinateModel.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ backend/CoordinateModel.h -o moc_CoordinateModel.cpp

moc_DS9Thread.cpp: backend/DS9Thread.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ backend/DS9Thread.h -o moc_DS9Thread.cpp

moc_EpoImage.cpp: backend/PPWcsImage.h \
		backend/EpoImage.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ backend/EpoImage.h -o moc_EpoImage.cpp

moc_ExportWCS.cpp: backend/EpoImage.h \
		backend/PPWcsImage.h \
		backend/ComputeWCS.h \
		backend/ExportWCS.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ backend/ExportWCS.h -o moc_ExportWCS.cpp

moc_FitsImage.cpp: backend/PPWcsImage.h \
		backend/FitsImage.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ backend/FitsImage.h -o moc_FitsImage.cpp

moc_FITSThread.cpp: backend/FitsImage.h \
		backend/PPWcsImage.h \
		backend/FITSThread.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ backend/FITSThread.h -o moc_FITSThread.cpp

moc_PPWcsImage.cpp: backend/PPWcsImage.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ backend/PPWcsImage.h -o moc_PPWcsImage.cpp

moc_AboutDialog.cpp: ui_AboutDialog.h \
		gui/AboutDialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/AboutDialog.h -o moc_AboutDialog.cpp

moc_CoordinatePanel.cpp: backend/PPWcsImage.h \
		ui_CoordinatePanel.h \
		gui/CoordinatePanel.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/CoordinatePanel.h -o moc_CoordinatePanel.cpp

moc_CoordinateTableDialog.cpp: ui_CoordinateTableDialog.h \
		gui/CoordinateTableDialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/CoordinateTableDialog.h -o moc_CoordinateTableDialog.cpp

moc_DropArea.cpp: gui/DropArea.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/DropArea.h -o moc_DropArea.cpp

moc_FitsToolbar.cpp: ui_FitsToolbar.h \
		gui/FitsToolbar.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/FitsToolbar.h -o moc_FitsToolbar.cpp

moc_GraphicsScene.cpp: gui/CoordinateMarker.h \
		gui/GraphicsView.h \
		gui/GraphicsScene.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/GraphicsScene.h -o moc_GraphicsScene.cpp

moc_GraphicsView.cpp: gui/GraphicsView.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/GraphicsView.h -o moc_GraphicsView.cpp

moc_HelpPanel.cpp: ui_HelpPanel.h \
		gui/HelpPanel.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/HelpPanel.h -o moc_HelpPanel.cpp

moc_mainwindow.cpp: ui_PinpointWCS.h \
		backend/FitsImage.h \
		backend/PPWcsImage.h \
		backend/EpoImage.h \
		gui/GraphicsScene.h \
		gui/CoordinateMarker.h \
		gui/GraphicsView.h \
		gui/WcsInfoPanel.h \
		gui/CoordinatePanel.h \
		ui_CoordinatePanel.h \
		gui/FitsToolbar.h \
		ui_FitsToolbar.h \
		backend/CoordinateModel.h \
		gui/Commands.h \
		backend/CoordinateDelegate.h \
		backend/ComputeWCS.h \
		gui/CoordinateTableDialog.h \
		ui_CoordinateTableDialog.h \
		backend/ExportWCS.h \
		gui/AboutDialog.h \
		ui_AboutDialog.h \
		gui/MessageBox.h \
		backend/FITSThread.h \
		backend/DS9Thread.h \
		gui/mainwindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/mainwindow.h -o moc_mainwindow.cpp

moc_MessageBox.cpp: gui/MessageBox.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/MessageBox.h -o moc_MessageBox.cpp

moc_WcsInfoPanel.cpp: gui/WcsInfoPanel.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gui/WcsInfoPanel.h -o moc_WcsInfoPanel.cpp

compiler_rcc_make_all: qrc_PinpointWCS.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_PinpointWCS.cpp
qrc_PinpointWCS.cpp: PinpointWCS.qrc \
		gui/style.qss \
		gui/images/logo.png \
		gui/images/logo.icns \
		gui/images/bad.png \
		gui/images/spindown-pressed.png \
		gui/images/spindown.png \
		gui/images/good.png
	/Developer/Tools/Qt/rcc -name PinpointWCS PinpointWCS.qrc -o qrc_PinpointWCS.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_AboutDialog.h ui_CoordinatePanel.h ui_CoordinateTableDialog.h ui_FitsToolbar.h ui_HelpPanel.h ui_PinpointWCS.h ui_WcsInfoPanel.h
compiler_uic_clean:
	-$(DEL_FILE) ui_AboutDialog.h ui_CoordinatePanel.h ui_CoordinateTableDialog.h ui_FitsToolbar.h ui_HelpPanel.h ui_PinpointWCS.h ui_WcsInfoPanel.h
ui_AboutDialog.h: gui/AboutDialog.ui
	/Developer/Tools/Qt/uic gui/AboutDialog.ui -o ui_AboutDialog.h

ui_CoordinatePanel.h: gui/CoordinatePanel.ui
	/Developer/Tools/Qt/uic gui/CoordinatePanel.ui -o ui_CoordinatePanel.h

ui_CoordinateTableDialog.h: gui/CoordinateTableDialog.ui
	/Developer/Tools/Qt/uic gui/CoordinateTableDialog.ui -o ui_CoordinateTableDialog.h

ui_FitsToolbar.h: gui/FitsToolbar.ui
	/Developer/Tools/Qt/uic gui/FitsToolbar.ui -o ui_FitsToolbar.h

ui_HelpPanel.h: gui/HelpPanel.ui
	/Developer/Tools/Qt/uic gui/HelpPanel.ui -o ui_HelpPanel.h

ui_PinpointWCS.h: gui/PinpointWCS.ui \
		gui/DropArea.h \
		gui/GraphicsView.h
	/Developer/Tools/Qt/uic gui/PinpointWCS.ui -o ui_PinpointWCS.h

ui_WcsInfoPanel.h: gui/WcsInfoPanel.ui
	/Developer/Tools/Qt/uic gui/WcsInfoPanel.ui -o ui_WcsInfoPanel.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp gui/mainwindow.h \
		ui_PinpointWCS.h \
		backend/FitsImage.h \
		backend/PPWcsImage.h \
		backend/EpoImage.h \
		gui/GraphicsScene.h \
		gui/CoordinateMarker.h \
		gui/GraphicsView.h \
		gui/WcsInfoPanel.h \
		gui/CoordinatePanel.h \
		ui_CoordinatePanel.h \
		gui/FitsToolbar.h \
		ui_FitsToolbar.h \
		backend/CoordinateModel.h \
		gui/Commands.h \
		backend/CoordinateDelegate.h \
		backend/ComputeWCS.h \
		gui/CoordinateTableDialog.h \
		ui_CoordinateTableDialog.h \
		backend/ExportWCS.h \
		gui/AboutDialog.h \
		ui_AboutDialog.h \
		gui/MessageBox.h \
		backend/FITSThread.h \
		backend/DS9Thread.h \
		version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ComputeWCS.o: backend/ComputeWCS.cpp backend/ComputeWCS.h \
		backend/PinpointWCSUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ComputeWCS.o backend/ComputeWCS.cpp

CoordinateDelegate.o: backend/CoordinateDelegate.cpp backend/CoordinateDelegate.h \
		gui/GraphicsScene.h \
		gui/CoordinateMarker.h \
		gui/GraphicsView.h \
		backend/CoordinateModel.h \
		gui/Commands.h \
		backend/ComputeWCS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CoordinateDelegate.o backend/CoordinateDelegate.cpp

CoordinateModel.o: backend/CoordinateModel.cpp backend/CoordinateModel.h \
		gui/Commands.h \
		gui/GraphicsScene.h \
		gui/CoordinateMarker.h \
		gui/GraphicsView.h \
		backend/CoordinateDelegate.h \
		backend/ComputeWCS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CoordinateModel.o backend/CoordinateModel.cpp

DS9Thread.o: backend/DS9Thread.cpp backend/DS9Thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DS9Thread.o backend/DS9Thread.cpp

EpoImage.o: backend/EpoImage.cpp backend/EpoImage.h \
		backend/PPWcsImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EpoImage.o backend/EpoImage.cpp

ExportWCS.o: backend/ExportWCS.cpp version.h \
		backend/ExportWCS.h \
		backend/EpoImage.h \
		backend/PPWcsImage.h \
		backend/ComputeWCS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExportWCS.o backend/ExportWCS.cpp

FitsImage.o: backend/FitsImage.cpp backend/FitsImage.h \
		backend/PPWcsImage.h \
		backend/PinpointWCSUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FitsImage.o backend/FitsImage.cpp

FITSThread.o: backend/FITSThread.cpp backend/FITSThread.h \
		backend/FitsImage.h \
		backend/PPWcsImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FITSThread.o backend/FITSThread.cpp

PinpointWCSUtils.o: backend/PinpointWCSUtils.cpp backend/PinpointWCSUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PinpointWCSUtils.o backend/PinpointWCSUtils.cpp

PPWcsImage.o: backend/PPWcsImage.cpp backend/PPWcsImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PPWcsImage.o backend/PPWcsImage.cpp

AboutDialog.o: gui/AboutDialog.cpp gui/AboutDialog.h \
		ui_AboutDialog.h \
		version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AboutDialog.o gui/AboutDialog.cpp

Commands.o: gui/Commands.cpp gui/Commands.h \
		gui/GraphicsScene.h \
		gui/CoordinateMarker.h \
		gui/GraphicsView.h \
		backend/CoordinateModel.h \
		backend/CoordinateDelegate.h \
		backend/ComputeWCS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Commands.o gui/Commands.cpp

CoordinateMarker.o: gui/CoordinateMarker.cpp gui/CoordinateMarker.h \
		gui/GraphicsScene.h \
		gui/GraphicsView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CoordinateMarker.o gui/CoordinateMarker.cpp

CoordinatePanel.o: gui/CoordinatePanel.cpp gui/CoordinatePanel.h \
		backend/PPWcsImage.h \
		ui_CoordinatePanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CoordinatePanel.o gui/CoordinatePanel.cpp

CoordinateTableDialog.o: gui/CoordinateTableDialog.cpp gui/CoordinateTableDialog.h \
		ui_CoordinateTableDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CoordinateTableDialog.o gui/CoordinateTableDialog.cpp

DropArea.o: gui/DropArea.cpp gui/DropArea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DropArea.o gui/DropArea.cpp

FitsToolbar.o: gui/FitsToolbar.cpp gui/FitsToolbar.h \
		ui_FitsToolbar.h \
		gui/CoordinatePanel.h \
		backend/PPWcsImage.h \
		ui_CoordinatePanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FitsToolbar.o gui/FitsToolbar.cpp

GraphicsScene.o: gui/GraphicsScene.cpp gui/GraphicsScene.h \
		gui/CoordinateMarker.h \
		gui/GraphicsView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GraphicsScene.o gui/GraphicsScene.cpp

GraphicsView.o: gui/GraphicsView.cpp gui/GraphicsView.h \
		gui/GraphicsScene.h \
		gui/CoordinateMarker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GraphicsView.o gui/GraphicsView.cpp

HelpPanel.o: gui/HelpPanel.cpp gui/HelpPanel.h \
		ui_HelpPanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HelpPanel.o gui/HelpPanel.cpp

mainwindow.o: gui/mainwindow.cpp gui/mainwindow.h \
		ui_PinpointWCS.h \
		backend/FitsImage.h \
		backend/PPWcsImage.h \
		backend/EpoImage.h \
		gui/GraphicsScene.h \
		gui/CoordinateMarker.h \
		gui/GraphicsView.h \
		gui/WcsInfoPanel.h \
		gui/CoordinatePanel.h \
		ui_CoordinatePanel.h \
		gui/FitsToolbar.h \
		ui_FitsToolbar.h \
		backend/CoordinateModel.h \
		gui/Commands.h \
		backend/CoordinateDelegate.h \
		backend/ComputeWCS.h \
		gui/CoordinateTableDialog.h \
		ui_CoordinateTableDialog.h \
		backend/ExportWCS.h \
		gui/AboutDialog.h \
		ui_AboutDialog.h \
		gui/MessageBox.h \
		backend/FITSThread.h \
		backend/DS9Thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o gui/mainwindow.cpp

MessageBox.o: gui/MessageBox.cpp gui/MessageBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MessageBox.o gui/MessageBox.cpp

WcsInfoPanel.o: gui/WcsInfoPanel.cpp gui/WcsInfoPanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WcsInfoPanel.o gui/WcsInfoPanel.cpp

moc_ComputeWCS.o: moc_ComputeWCS.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ComputeWCS.o moc_ComputeWCS.cpp

moc_CoordinateDelegate.o: moc_CoordinateDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CoordinateDelegate.o moc_CoordinateDelegate.cpp

moc_CoordinateModel.o: moc_CoordinateModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CoordinateModel.o moc_CoordinateModel.cpp

moc_DS9Thread.o: moc_DS9Thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DS9Thread.o moc_DS9Thread.cpp

moc_EpoImage.o: moc_EpoImage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EpoImage.o moc_EpoImage.cpp

moc_ExportWCS.o: moc_ExportWCS.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ExportWCS.o moc_ExportWCS.cpp

moc_FitsImage.o: moc_FitsImage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FitsImage.o moc_FitsImage.cpp

moc_FITSThread.o: moc_FITSThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FITSThread.o moc_FITSThread.cpp

moc_PPWcsImage.o: moc_PPWcsImage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PPWcsImage.o moc_PPWcsImage.cpp

moc_AboutDialog.o: moc_AboutDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AboutDialog.o moc_AboutDialog.cpp

moc_CoordinatePanel.o: moc_CoordinatePanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CoordinatePanel.o moc_CoordinatePanel.cpp

moc_CoordinateTableDialog.o: moc_CoordinateTableDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CoordinateTableDialog.o moc_CoordinateTableDialog.cpp

moc_DropArea.o: moc_DropArea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DropArea.o moc_DropArea.cpp

moc_FitsToolbar.o: moc_FitsToolbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FitsToolbar.o moc_FitsToolbar.cpp

moc_GraphicsScene.o: moc_GraphicsScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GraphicsScene.o moc_GraphicsScene.cpp

moc_GraphicsView.o: moc_GraphicsView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GraphicsView.o moc_GraphicsView.cpp

moc_HelpPanel.o: moc_HelpPanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HelpPanel.o moc_HelpPanel.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_MessageBox.o: moc_MessageBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MessageBox.o moc_MessageBox.cpp

moc_WcsInfoPanel.o: moc_WcsInfoPanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WcsInfoPanel.o moc_WcsInfoPanel.cpp

qrc_PinpointWCS.o: qrc_PinpointWCS.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_PinpointWCS.o qrc_PinpointWCS.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

